### ISSUE TITLE
Eth_btc and eth_usd

### ISSUE THREAD

**Issue by JeffOnGithub** [joowani/quadriga#1]
Hello,

The lib checks for eth_usd which do not exist on Quadriga.

It is missing eth_btc which does exist.

I've edited the lib and it all works correctly bt changing the name.

**Comment by joowani** [comment]
Hi @JeffOnGithub,

Ah right. Thanks for pointing that out. 
Ill make a fix for it in the next release.

Thanks,
Joohwan

**Comment by joowani** [comment]
Hi @JeffOnGithub 

I've corrected the issue in the newest release: https://github.com/joowani/quadriga/releases/tag/1.3.1

Thanks!
