### ISSUE TITLE
Quadriga broke this?

### ISSUE THREAD

**Issue by jcbrown22** [joowani/quadriga#4]
Hi!
Thanks so much for creating this, it's exactly what I was looking for. However, I can't seem to get it working (I'm admittedly a Python newb, so that might be related), but my code looks like that below, and I get zero output whatsoever:
Sorry if this is a really elementary question, I know you're not here to babysit new users, but I wanted to double check that this wasn't something that Quadriga had changed recently that may have broken some functionality?
```
from quadriga import QuadrigaClient

# Initialize without the credentials or the client ID
client = QuadrigaClient(default_book='btc_usd')

# Public API calls are allowed
client.get_summary()
client.get_public_orders()
client.get_public_trades()
```

**Comment by joowani** [comment]
Hi @jcbrown22,

How are you running the python code exactly? Are you using something interactive like `ipython` or running it in an `.py` file? If it's the latter and you are expecting to see something in stdout, you will need to do something like this:

```python
from quadriga import QuadrigaClient

client = QuadrigaClient(default_book='btc_usd')

# You have to explicitly print the result to stdout
print(client.get_summary())
```

Let me know if that works for you.

Best,
Joohwan

**Comment by jcbrown22** [comment]
Perfect, thank you! And thank you for taking the time to help a Python newcomer!
Cheers,
JCB
