### ISSUE TITLE
[HTTP 200][ERR 104] nonce must be higher than 15141934782042

### ISSUE THREAD

**Issue by maxim25** [joowani/quadriga#5]
Hi,

Not sure why this would be an issue however I am getting the following error.

> [HTTP 200][ERR 104] Cannot perform request - nonce must be higher than 15141934782042

Changing the following line to * 10000 fixes the issue:

https://github.com/joowani/quadriga/blob/ba1591eead956923c500c92d10804088650c07b8/quadriga/rest_client.py#L118

Cheers

**Comment by joowani** [comment]
Hi @maxim25,

Ok that's good to know. I will add the fix to the new release I'm working on.

Thanks!

**Comment by joowani** [comment]
Issue is now fixed in version [2.0.0](https://github.com/joowani/quadriga/releases/tag/2.0.0).
